on: [push]

jobs:
  soos_dast_analysis_example:
    name: SOOS DAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Analysis
        uses: soos-io/soos-dast-github-action@v1.1.1
        with:
          client_id: wq2phap3l
          api_key: ZTY0OTdlNzYtNTRlNy00YWJkLWExNjQtMGU1NTI1M2YzNzQw
          project_name: "DAST-GitHub-Action-Test"
          scan_mode: "baseline"
          api_url: "https://api.soos.io/api/"
          target_url: "https://github.com/snyk/java-reachability-playground"
